title: Purnima Tammireddy
email: purnimat07@gmail.com
description: >-
  Author, translator, publisher.
baseurl: ""
url: "https://purnima215.github.io"
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

minimal_mistakes_skin: "purnima"

header_pages:
  - index.md
  - _pages/about.md
  - _pages/books.md
  - _pages/media.md
  - _pages/events.md
  - _pages/contact.md

custom_css:
  - /assets/css/custom.css
