title: Purnima Tammireddy
email: purnimat07@gmail.com
description: >-
  Author, translator, publisher.
baseurl: ""
url: "https://purnima215.github.io"
theme: minimal-mistakes-jekyll

collections:
  pages:
    output: true
    permalink: /:basename/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

minimal_mistakes_skin: "purnima"

header_pages:
  - index.md
  - _pages/about.md
  - _pages/books.md
  - _pages/media.md
  - _pages/events.md
  - _pages/contact.md

custom_css:
  - /assets/css/custom.css

include: ["_includes"]