title: Purnima Tammireddy
email: purnimat07@gmail.com
description: >-
  Author, translator, publisher.
baseurl: ""
url: "https://purnima215.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

minimal_mistakes_skin: "default"

header_pages:
  - index.md
  - _pages/about.md
  - _pages/books.md
  - _pages/media.md
  - _pages/events.md
  - _pages/contact.md
